name: Hub E2E Tests on Chrome
on: 
 workflow_dispatch:
 schedule:
    - cron: '43 16 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
     image: cypress/browsers:node16.5.0-chrome97-ff96
     options: --user 1001
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - run: npm install 
      - name: Cypress run
        id: cypresstest
        run: | 
          npm run cy:run:smoke:alpha >> changed-fields.out 
          OUTPUT1=`tail -n 50 changed-fields.out`
          OUTPUT1="${OUTPUT1//'%'/'%25'}"
          OUTPUT1="${OUTPUT1//$'\n'/'%0A'}"
          OUTPUT1="${OUTPUT1//$'\r'/'%0D'}"
          echo "before 1"
          echo "$OUTPUT1"
          echo "::set-output name=result::$OUTPUT1"
          echo "OUTPUT=$OUTPUT1" >> $GITHUB_ENV
          echo "after 1"
          echo "${{ env.OUTPUT }}"
        continue-on-error: true
      - run: |
          npm run e2e:reports 
      - name: print output 
        run: 
          echo "${{ env.OUTPUT }}"
          echo "after environment output"
          echo ${{ steps.cypresstest.outputs.result }}
      - name: Store results   
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots   
      - name: Store reports   
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test reports
          path: test-reports  
      - name: Send Slack message on failure
        uses: archive/github-actions-slack@v2.0.0
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C034FNUA7SA
          slack-text:  |
           Admin cypress tests finished with ${{ steps.cypresstest.outcome }} 
           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           ${{ env.output }}
      - name: Send Slack message 
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C034FNUA7SA
          slack-text: |
           Admin cypress tests finished with ${{ steps.cypresstest.outcome }} 
           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           ${{ env.output }}

