name: Hub E2E Tests on Chrome
on: 
 schedule:
    - cron: '02 15 * * *'
jobs:
  cypress-run:
    runs-on: windows-latest
    container: cypress/browsers:node16.5.0-chrome97-ff96

    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
     - name: Checkout 
       uses: actions/checkout@v2

     - name: Custom tests 
       uses: cypress-io/github-action@v2
       with:
         command: npm run cy:run:smoke:alpha
     - name: Store results   
       uses: actions/upload-artifact@v2
       if: failure()
       with:
          name: cypress-screenshots
          path: cypress/screenshots 